//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBiEmbeddedScratchpad.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBiEmbeddedScratchpad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///  margin: 0;
        ///  padding: 0;
        ///  background-color: #EEE;
        ///}
        ///
        ///#toolbar {
        ///  padding: 8px;
        ///  background-color: black;
        ///}
        ///
        ///  #toolbar button {
        ///    font-size: 24px;
        ///    width: 150px
        ///  }
        ///
        ///#leftnav {
        ///  float: left;
        ///  width: 240px;
        ///  background-color: white;
        ///  padding: 0px;
        ///  border: solid 1px #333;
        ///}
        ///
        ///#leftnav h3 {
        ///  margin: 0;
        ///  padding: 4px;
        ///  padding-left: 12px;
        ///  color: white;
        ///  background-color: black;
        ///  font-size: 24px;
        ///}
        ///
        ///  #leftnav h4 {
        ///    margin: 0;
        ///    padding: 4px;
        ///    padding-bottom: 2px;
        ///    padding [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string app_css {
            get {
                return ResourceManager.GetString("app_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppIcon_png {
            get {
                object obj = ResourceManager.GetObject("AppIcon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedDashboardId = &quot;@EmbedDashboardId&quot;;
        ///    var embedUrl = &quot;@Emb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedDashboard_html {
            get {
                return ResourceManager.GetString("EmbedDashboard_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedDashboardId = &quot;@EmbedDashboardId&quot;;
        ///    var embedTileId = &quot;@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedDashboardTile_html {
            get {
                return ResourceManager.GetString("EmbedDashboardTile_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // Get data required for embedding
        ///    var embedWorkspaceId= &quot;@EmbedW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedNewReport_html {
            get {
                return ResourceManager.GetString("EmbedNewReport_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;toolbar&quot; hidden&gt;
        ///    &lt;button type=&quot;button&quot; id=&quot;toggleEdit&quot; style=&quot;font-size:14px&quot;&gt;Toggle Edit M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedNewReportWithSaveAsRedirect_html {
            get {
                return ResourceManager.GetString("EmbedNewReportWithSaveAsRedirect_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;QNA Demo&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // Get data required for embedding
        ///    var datasetId = &quot;@DatasetId&quot;;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedQna_html {
            get {
                return ResourceManager.GetString("EmbedQna_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedReportId = &quot;@EmbedReportId&quot;;
        ///    var embedUrl = &quot;@EmbedUrl&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReport_html {
            get {
                return ResourceManager.GetString("EmbedReport_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedReportId = &quot;@EmbedReportId&quot;;
        ///    var embedUrl = &quot;@EmbedUrl&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportVisual_html {
            get {
                return ResourceManager.GetString("EmbedReportVisual_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;Navigating with Bookmarks&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///  &lt;div id=&quot;leftnav&quot; style=&quot;float:left; width:240px;&quot;&gt;
        ///    &lt;h3&gt;Bookmarks&lt;/h3&gt;
        ///    &lt;div id=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithBookmarkCarousel_html {
            get {
                return ResourceManager.GetString("EmbedReportWithBookmarkCarousel_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;Navigating with Bookmarks&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///  &lt;div id=&quot;leftnav&quot; style=&quot;float:left; width:240px;&quot;&gt;
        ///    &lt;h3&gt;Bookmarks&lt;/h3&gt;
        ///    &lt;div id=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithBookmarks_html {
            get {
                return ResourceManager.GetString("EmbedReportWithBookmarks_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///
        ///  &lt;style&gt;
        ///    #embedContainer iframe { background-color: white; }
        ///  &lt;/style&gt;
        ///
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithConfigurationOptions_html {
            get {
                return ResourceManager.GetString("EmbedReportWithConfigurationOptions_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;Context Menu Demo&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;reportContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithContextMenus_html {
            get {
                return ResourceManager.GetString("EmbedReportWithContextMenus_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;Custom Filtering Demo&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;leftnav&quot; style=&quot;float:left;&quot; &gt;
        ///
        ///    &lt;h3&gt;Custom Filtering &lt;/h3&gt;
        ///
        ///    &lt;div id=&quot;loading&quot; hidden [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithCustomFiltering_html {
            get {
                return ResourceManager.GetString("EmbedReportWithCustomFiltering_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedReportId = &quot;@EmbedReportId&quot;;
        ///    var embedUrl = &quot;@EmbedUrl&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithFirstPartyToken_html {
            get {
                return ResourceManager.GetString("EmbedReportWithFirstPartyToken_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///  &lt;div id=&quot;leftnav&quot; style=&quot;float:left; width:240px;&quot;&gt;
        ///    &lt;h3&gt;Page Navigation&lt;/h3&gt;
        ///    &lt;div id=&quot;loading&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithPageNavigation_html {
            get {
                return ResourceManager.GetString("EmbedReportWithPageNavigation_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName - Phased Loading&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///
        ///    // preload preload pbie scripts on this page
        ///    var preloadConfig = {
        ///      type: &apos;report&apos;,
        ///      ba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithPhasedLoading_html {
            get {
                return ResourceManager.GetString("EmbedReportWithPhasedLoading_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;toolbar&quot;&gt;
        ///    &lt;button type=&quot;button&quot; id=&quot;toggleEdit&quot; style=&quot;font-size:14px&quot; &gt;Toggle Edit Mode&lt;/button&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithRLS_html {
            get {
                return ResourceManager.GetString("EmbedReportWithRLS_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;toolbar&quot;&gt;
        ///    &lt;button type=&quot;button&quot; id=&quot;toggleEdit&quot; style=&quot;font-size:14px&quot;&gt;Toggle Edit Mode&lt;/button&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithToolbar_html {
            get {
                return ResourceManager.GetString("EmbedReportWithToolbar_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] favicon_ico {
            get {
                object obj = ResourceManager.GetObject("favicon_ico", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v3.3.1
        /// * https://jquery.com/
        /// *
        /// * Includes Sizzle.js
        /// * https://sizzlejs.com/
        /// *
        /// * Copyright JS Foundation and other contributors
        /// * Released under the MIT license
        /// * https://jquery.org/license
        /// *
        /// * Date: 2018-01-20T17:24Z
        /// */
        ///( function( global, factory ) {
        ///
        ///	&quot;use strict&quot;;
        ///
        ///	if ( typeof module === &quot;object&quot; &amp;&amp; typeof module.exports === &quot;object&quot; ) {
        ///
        ///		// For CommonJS and CommonJS-like environments where a proper `window`
        ///		// is present, execute the factory and get jQuer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_js {
            get {
                return ResourceManager.GetString("jquery_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] loading_gif {
            get {
                object obj = ResourceManager.GetObject("loading_gif", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] loading2_gif {
            get {
                object obj = ResourceManager.GetObject("loading2_gif", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] loading3_gif {
            get {
                object obj = ResourceManager.GetObject("loading3_gif", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! powerbi-client v2.6.0 | (c) 2016 Microsoft Corporation MIT */
        ///(function webpackUniversalModuleDefinition(root, factory) {
        ///	if(typeof exports === &apos;object&apos; &amp;&amp; typeof module === &apos;object&apos;)
        ///		module.exports = factory();
        ///	else if(typeof define === &apos;function&apos; &amp;&amp; define.amd)
        ///		define([], factory);
        ///	else if(typeof exports === &apos;object&apos;)
        ///		exports[&quot;powerbi-client&quot;] = factory();
        ///	else
        ///		root[&quot;powerbi-client&quot;] = factory();
        ///})(this, function() {
        ///return /******/ (function(modules) { // webpackBootstrap
        ////******/ 	// Th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string powerbi_js {
            get {
                return ResourceManager.GetString("powerbi_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;Report Inspector&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;output-display&quot; style=&quot;float:right; width:400px; overflow: auto;&quot;&gt;&lt;/div&gt;
        ///
        ///  &lt;div id=&quot;embedContainerContainer&quot; style=&quot;margin-right:400px&quot;&gt;
        ///    &lt;div  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportInspector_html {
            get {
                return ResourceManager.GetString("ReportInspector_html", resourceCulture);
            }
        }
    }
}
